"""Phase 2: digital twin schema (spec §13)

Creates the Phase 2 subset of the platform data model plus the database-level
guarantees the spec requires: append-only immutable event history, idempotency
uniqueness on event ids, and value constraints.

Revision ID: 4b82d59e4c3e
Revises:
Create Date: 2026-08-18 02:10:41.624873+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4b82d59e4c3e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("home_id", sa.String(length=64), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_events_home_occurred", "audit_events", ["home_id", "occurred_at"], unique=False
    )
    op.create_table(
        "device_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("home_id", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=True),
        sa.Column("entity_id", sa.String(length=256), nullable=True),
        sa.Column("room_id", sa.String(length=64), nullable=True),
        sa.Column("capability", sa.String(length=64), nullable=True),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("quality", sa.Float(), nullable=False),
        sa.Column("privacy_class", sa.String(length=32), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=True),
        sa.Column("causation_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("quality >= 0 AND quality <= 1", name="ck_device_events_quality"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", name="uq_device_events_event_id"),
    )
    op.create_index(
        "ix_device_events_device_capability",
        "device_events",
        ["device_id", "capability"],
        unique=False,
    )
    op.create_index(op.f("ix_device_events_event_id"), "device_events", ["event_id"], unique=False)
    op.create_index(op.f("ix_device_events_home_id"), "device_events", ["home_id"], unique=False)
    op.create_index(
        "ix_device_events_home_occurred", "device_events", ["home_id", "occurred_at"], unique=False
    )
    op.create_table(
        "homes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("home_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_homes_home_id"), "homes", ["home_id"], unique=True)
    op.create_table(
        "system_health_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hub_id", sa.String(length=64), nullable=False),
        sa.Column("service", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_health_events_hub_id"), "system_health_events", ["hub_id"], unique=False
    )
    op.create_table(
        "twin_checkpoints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("home_id", sa.String(length=64), nullable=False),
        sa.Column("stream_sequence", sa.Integer(), nullable=False),
        sa.Column("events_applied", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_twin_checkpoints_home_id"), "twin_checkpoints", ["home_id"], unique=True
    )
    op.create_table(
        "hubs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hub_id", sa.String(length=64), nullable=False),
        sa.Column("home_uuid", sa.Uuid(), nullable=False),
        sa.Column("software_version", sa.String(length=64), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["home_uuid"], ["homes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hubs_hub_id"), "hubs", ["hub_id"], unique=True)
    op.create_table(
        "rooms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("home_uuid", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(["home_uuid"], ["homes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("home_uuid", "room_id", name="uq_rooms_home_room"),
    )
    op.create_index(op.f("ix_rooms_room_id"), "rooms", ["room_id"], unique=False)
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("home_uuid", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("manufacturer", sa.String(length=200), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("room_uuid", sa.Uuid(), nullable=True),
        sa.Column("available", sa.Boolean(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["home_uuid"], ["homes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["room_uuid"], ["rooms.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("home_uuid", "device_id", name="uq_devices_home_device"),
    )
    op.create_index(op.f("ix_devices_device_id"), "devices", ["device_id"], unique=False)
    op.create_table(
        "room_relationships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("from_room_uuid", sa.Uuid(), nullable=False),
        sa.Column("to_room_uuid", sa.Uuid(), nullable=False),
        sa.Column("relationship_type", sa.String(length=32), nullable=False),
        sa.CheckConstraint("from_room_uuid <> to_room_uuid", name="ck_room_relationship_not_self"),
        sa.ForeignKeyConstraint(["from_room_uuid"], ["rooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_room_uuid"], ["rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "from_room_uuid", "to_room_uuid", "relationship_type", name="uq_room_relationship"
        ),
    )
    op.create_table(
        "device_capabilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_uuid", sa.Uuid(), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("safety_class", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["device_uuid"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_uuid", "capability", name="uq_device_capabilities"),
    )
    op.create_index(
        op.f("ix_device_capabilities_capability"),
        "device_capabilities",
        ["capability"],
        unique=False,
    )
    op.create_table(
        "device_current_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("home_uuid", sa.Uuid(), nullable=False),
        sa.Column("device_uuid", sa.Uuid(), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("quality", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_event_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "status IN ('UNKNOWN', 'KNOWN', 'STALE')", name="ck_current_state_status"
        ),
        sa.CheckConstraint("quality >= 0 AND quality <= 1", name="ck_current_state_quality"),
        sa.ForeignKeyConstraint(["device_uuid"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["home_uuid"], ["homes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_uuid", "capability", name="uq_current_state"),
    )
    op.create_index(
        "ix_current_states_capability", "device_current_states", ["capability"], unique=False
    )
    op.create_table(
        "device_entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_uuid", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.String(length=256), nullable=False),
        sa.Column("integration", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["device_uuid"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_uuid", "entity_id", name="uq_device_entities_device_entity"),
    )
    op.create_index(
        op.f("ix_device_entities_entity_id"), "device_entities", ["entity_id"], unique=False
    )
    op.create_table(
        "device_vendor_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_uuid", sa.Uuid(), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("integration", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=256), nullable=True),
        sa.Column("service_domain", sa.String(length=64), nullable=True),
        sa.Column("service_name", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["device_uuid"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_uuid", "capability", "integration", name="uq_vendor_mapping"),
    )
    # ### end Alembic commands ###

    # Spec §13.1: immutable events are append-only, and the audit trail is
    # immutable (§25.5). Enforced by the database so no service — and no
    # future bug — can rewrite recorded history.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION syltra_forbid_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'table % is append-only; % is not permitted',
                TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in ("device_events", "audit_events"):
        op.execute(
            f"""
            CREATE TRIGGER {table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION syltra_forbid_mutation();
            """
        )


def downgrade() -> None:
    for table in ("device_events", "audit_events"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table};")
    op.execute("DROP FUNCTION IF EXISTS syltra_forbid_mutation();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("device_vendor_mappings")
    op.drop_index(op.f("ix_device_entities_entity_id"), table_name="device_entities")
    op.drop_table("device_entities")
    op.drop_index("ix_current_states_capability", table_name="device_current_states")
    op.drop_table("device_current_states")
    op.drop_index(op.f("ix_device_capabilities_capability"), table_name="device_capabilities")
    op.drop_table("device_capabilities")
    op.drop_table("room_relationships")
    op.drop_index(op.f("ix_devices_device_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_rooms_room_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_hubs_hub_id"), table_name="hubs")
    op.drop_table("hubs")
    op.drop_index(op.f("ix_twin_checkpoints_home_id"), table_name="twin_checkpoints")
    op.drop_table("twin_checkpoints")
    op.drop_index(op.f("ix_system_health_events_hub_id"), table_name="system_health_events")
    op.drop_table("system_health_events")
    op.drop_index(op.f("ix_homes_home_id"), table_name="homes")
    op.drop_table("homes")
    op.drop_index("ix_device_events_home_occurred", table_name="device_events")
    op.drop_index(op.f("ix_device_events_home_id"), table_name="device_events")
    op.drop_index(op.f("ix_device_events_event_id"), table_name="device_events")
    op.drop_index("ix_device_events_device_capability", table_name="device_events")
    op.drop_table("device_events")
    op.drop_index("ix_audit_events_home_occurred", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
