"""The checked-in OpenAPI document must match the routes (spec §21).

A specification that is regenerated by hand is a specification that is wrong,
and nobody notices until an integrator builds against it. These tests fail the
build the moment a route changes without `make openapi` being run.
"""

import json
from pathlib import Path

import pytest
from syltra_api_gateway.api import API_VERSION
from syltra_api_gateway.openapi_export import build_document, document_path

pytestmark = pytest.mark.contract

ROOT = Path(__file__).resolve().parents[3]


def test_the_checked_in_document_matches_the_routes() -> None:
    path = document_path(ROOT)
    assert path.exists(), f"{path} is missing; run 'make openapi'"
    checked_in = json.loads(path.read_text(encoding="utf-8"))
    assert checked_in == build_document(), "OpenAPI document is stale; run 'make openapi'"


def test_the_document_is_versioned_by_the_api_version() -> None:
    document = build_document()
    assert document["info"]["version"] == API_VERSION
    assert f"v{API_VERSION}" in document_path(ROOT).parts


# Every route that does not carry `{home_id}` in its path, and why each one is
# allowed to. A new entry here is a deliberate decision; a new route that lands
# outside both lists fails the build rather than quietly widening the surface.
NOT_PATH_SCOPED = {
    "/health/live": "liveness probe — no reader, no data",
    "/health/ready": "readiness probe — no reader, no data",
    "/metrics": "Prometheus scrape — counters, no household values",
    "/v1/health": "hub health for the console's System Health screen",
    "/v1/system/status": "hub identity and dispatch mode",
    "/v1/me": "who the caller is; scoping it to a home would be circular",
    "/v1/audit": "home-scoped by a required home_id query parameter, not by path",
}


def test_the_set_of_routes_outside_a_home_scope_is_the_expected_one() -> None:
    """Spec §14.9 and §21: reads are home-scoped unless there is a reason."""
    routes = set(build_document()["paths"])
    unscoped = {route for route in routes if "{home_id}" not in route}
    assert unscoped == set(NOT_PATH_SCOPED), (
        "a route appeared outside a home scope without a recorded reason: "
        f"{sorted(unscoped ^ set(NOT_PATH_SCOPED))}"
    )


def test_the_audit_route_still_requires_a_home() -> None:
    """It is exempt from path scoping only because the query parameter scopes it."""
    parameters = build_document()["paths"]["/v1/audit"]["get"]["parameters"]
    home = [p for p in parameters if p["name"] == "home_id"]
    assert home and home[0]["required"] and home[0]["in"] == "query"


def test_the_websocket_stream_is_absent_and_that_is_a_known_limitation() -> None:
    """OpenAPI 3.1 has no way to describe a WebSocket.

    `/v1/stream` is a real, authenticated endpoint that this document cannot
    carry. Asserting the absence keeps it a known limitation rather than a
    reader's wrong conclusion that the endpoint does not exist.
    """
    assert "/v1/stream" not in build_document()["paths"]


def test_the_export_contains_no_household_data() -> None:
    """It is generated from an empty platform, and must stay that way.

    A document built from a seeded gateway would carry example values lifted
    from whatever home happened to be loaded.
    """
    serialized = json.dumps(build_document())
    for leak in ("home_dev_001", "living_room", "27.4"):
        assert leak not in serialized, f"the exported document contains {leak}"
