"""Canonical SYLTRA contracts shared by every platform service.

This package is the single source of truth for the vocabulary defined in the
master build specification: the event envelope (§11), the capability registry
(§10), and the safety, privacy, policy, risk, and learning-mode enums. Services
must import these rather than redefining strings locally.
"""

from syltra_contracts.scenes import MAX_STEPS, SECURING_VALUES, Scene, SceneStep
from syltra_contracts.automations import (
    AUTOMATABLE_SAFETY_CLASSES,
    DEFAULT_ACTION_TTL,
    MINIMUM_REARM,
    Automation,
    AutomationAction,
    AutomationCondition,
    AutomationSource,
    AutomationTrigger,
    ConditionKind,
    TriggerKind,
)
from syltra_contracts.capabilities import (
    ACTUATOR_CAPABILITIES,
    ALL_CAPABILITIES,
    SENSOR_CAPABILITIES,
    is_known_capability,
)
from syltra_contracts.enums import (
    LearningMode,
    PolicyOutcome,
    PrivacyClass,
    RiskCategory,
    RiskState,
    SafetyClass,
)
from syltra_contracts.contexts import (
    ADVISORY_ONLY_CONTEXTS,
    ContextRecord,
    ContextType,
    EvidenceItem,
    home_scope,
    room_scope,
)
from syltra_contracts.actions import (
    ActionAttempt,
    ActionRequest,
    ActionResult,
    ActionStatus,
    ActionTarget,
    ExpectedState,
    FailureKind,
    derive_idempotency_key,
)
from syltra_contracts.deadletter import DeadLetterRecord
from syltra_contracts.feedback import (
    NEGATIVE_FEEDBACK,
    SUPPRESSING_FEEDBACK,
    FeedbackKind,
    FeedbackRecord,
    FeedbackSource,
)
from syltra_contracts.policy import POLICY_VERSION, PolicyDecision, compute_input_hash
from syltra_contracts.risk import (
    AI_REACHABLE_STATES,
    CERTIFIED_ALARM_CAPABILITIES,
    DEFAULT_PRE_ALERT_TTL,
    DEFAULT_WATCH_TTL,
    DETERMINISTIC_ONLY_STATES,
    EvidenceOrigin,
    RiskCase,
    RiskEvidenceItem,
    RiskSeverity,
    RiskTransitionError,
    UnauthorizedRiskTransition,
)
from syltra_contracts.risk import assert_transition as assert_risk_transition
from syltra_contracts.risk import can_transition as can_risk_transition
from syltra_contracts.models_registry import (
    LearningModeTransitionError,
    ModelCard,
    ModelStatus,
    ModelType,
    ModelVersion,
    TrainingWindow,
    allows_execution,
    allows_recommendations,
    allows_unattended_execution,
    assert_transition,
    can_transition,
)
from syltra_contracts.recommendations import (
    ModelReference,
    Recommendation,
    RecommendationTarget,
)
from syltra_contracts.events import (
    EVENT_TYPES,
    SCHEMA_VERSION,
    EventEnvelope,
    EventSource,
    EventSubject,
)
from syltra_contracts.gateway import (
    CapabilityCommand,
    CommandResult,
    DeviceHealth,
    DeviceInfo,
    DeviceIntegrationGateway,
    EntityInfo,
    EntityState,
    RegistrySnapshot,
)

__all__ = [
    "AUTOMATABLE_SAFETY_CLASSES",
    "MAX_STEPS",
    "SECURING_VALUES",
    "Automation",
    "AutomationAction",
    "AutomationCondition",
    "AutomationSource",
    "Scene",
    "SceneStep",
    "AutomationTrigger",
    "ConditionKind",
    "DEFAULT_ACTION_TTL",
    "MINIMUM_REARM",
    "TriggerKind",
    "ACTUATOR_CAPABILITIES",
    "ALL_CAPABILITIES",
    "EVENT_TYPES",
    "SCHEMA_VERSION",
    "SENSOR_CAPABILITIES",
    "ADVISORY_ONLY_CONTEXTS",
    "AI_REACHABLE_STATES",
    "CERTIFIED_ALARM_CAPABILITIES",
    "DEFAULT_PRE_ALERT_TTL",
    "DEFAULT_WATCH_TTL",
    "DETERMINISTIC_ONLY_STATES",
    "NEGATIVE_FEEDBACK",
    "POLICY_VERSION",
    "SUPPRESSING_FEEDBACK",
    "ActionAttempt",
    "ActionRequest",
    "ActionResult",
    "ActionStatus",
    "ActionTarget",
    "CapabilityCommand",
    "ContextRecord",
    "ContextType",
    "CommandResult",
    "DeadLetterRecord",
    "DeviceHealth",
    "DeviceInfo",
    "DeviceIntegrationGateway",
    "EntityInfo",
    "EntityState",
    "EventEnvelope",
    "EventSource",
    "EventSubject",
    "EvidenceItem",
    "EvidenceOrigin",
    "RiskCase",
    "RiskEvidenceItem",
    "RiskSeverity",
    "RiskTransitionError",
    "UnauthorizedRiskTransition",
    "ExpectedState",
    "FailureKind",
    "FeedbackKind",
    "FeedbackRecord",
    "FeedbackSource",
    "PolicyDecision",
    "LearningModeTransitionError",
    "ModelCard",
    "ModelReference",
    "ModelStatus",
    "ModelType",
    "ModelVersion",
    "Recommendation",
    "RecommendationTarget",
    "TrainingWindow",
    "RegistrySnapshot",
    "LearningMode",
    "PolicyOutcome",
    "PrivacyClass",
    "RiskCategory",
    "RiskState",
    "SafetyClass",
    "assert_risk_transition",
    "can_risk_transition",
    "compute_input_hash",
    "derive_idempotency_key",
    "allows_execution",
    "allows_recommendations",
    "allows_unattended_execution",
    "assert_transition",
    "can_transition",
    "home_scope",
    "is_known_capability",
    "room_scope",
]
