"""Phase 8: decisions, actions, feedback and risk cases (spec §13)

Completes the spec §13 model and extends the append-only guarantee to the
records a household is asked to trust: policy decisions, action requests and
results, feedback, and risk cases. A decision that can be rewritten after the
fact is not an audit record (safety invariant 12).

Revision ID: f1a51e380020
Revises: 4b82d59e4c3e
Create Date: 2026-08-19 16:10:05.381080+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f1a51e380020"
down_revision: str | None = "4b82d59e4c3e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("dispatched", sa.Boolean(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("failure_kind", sa.String(length=16), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_action_attempts_action_id"), "action_attempts", ["action_id"], unique=False
    )
    op.create_table(
        "action_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("home_id", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("previous_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("safety_class", sa.String(length=32), nullable=False),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_action_requests_idempotency"),
    )
    op.create_index(
        op.f("ix_action_requests_action_id"), "action_requests", ["action_id"], unique=False
    )
    op.create_index(
        op.f("ix_action_requests_decision_id"), "action_requests", ["decision_id"], unique=False
    )
    op.create_index(
        "ix_action_requests_home_created",
        "action_requests",
        ["home_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_requests_home_id"), "action_requests", ["home_id"], unique=False
    )
    op.create_table(
        "action_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("home_id", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("observed_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("compensated", sa.Boolean(), nullable=False),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action_id", name="uq_action_results_action"),
    )
    op.create_index(
        op.f("ix_action_results_action_id"), "action_results", ["action_id"], unique=False
    )
    op.create_index(
        "ix_action_results_home_completed",
        "action_results",
        ["home_id", "completed_at"],
        unique=False,
    )
    op.create_index(op.f("ix_action_results_home_id"), "action_results", ["home_id"], unique=False)
    op.create_table(
        "context_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("context_id", sa.Uuid(), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=True),
        sa.Column("room_id", sa.String(length=64), nullable=True),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_context_evidence_context_id"), "context_evidence", ["context_id"], unique=False
    )
    op.create_table(
        "contexts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("context_id", sa.Uuid(), nullable=False),
        sa.Column("home_id", sa.String(length=64), nullable=False),
        sa.Column("context_type", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=128), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("producer", sa.String(length=128), nullable=False),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("context_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_contexts_confidence"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contexts_context_id"), "contexts", ["context_id"], unique=False)
    op.create_index(op.f("ix_contexts_home_id"), "contexts", ["home_id"], unique=False)
    op.create_index(
        "ix_contexts_home_started", "contexts", ["home_id", "started_at"], unique=False
    )
    op.create_index("ix_contexts_home_type", "contexts", ["home_id", "context_type"], unique=False)
    op.create_table(
        "manual_overrides",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("home_id", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_action_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_manual_overrides_home_at", "manual_overrides", ["home_id", "occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_manual_overrides_home_id"), "manual_overrides", ["home_id"], unique=False
    )
    op.create_table(
        "policy_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("recommendation_id", sa.Uuid(), nullable=True),
        sa.Column("home_id", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=40), nullable=False),
        sa.Column("safety_class", sa.String(length=32), nullable=False),
        sa.Column("policy_version", sa.String(length=16), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('ALLOW','DENY','REQUIRE_USER_APPROVAL',"
            "'PREPARE_ONLY','ESCALATE_TO_FIXED_SAFETY_RULE')",
            name="ck_policy_decision_outcome",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("decision_id", name="uq_policy_decisions_id"),
    )
    op.create_index(
        op.f("ix_policy_decisions_decision_id"), "policy_decisions", ["decision_id"], unique=False
    )
    op.create_index(
        "ix_policy_decisions_home_evaluated",
        "policy_decisions",
        ["home_id", "evaluated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_decisions_home_id"), "policy_decisions", ["home_id"], unique=False
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("home_id", sa.String(length=64), nullable=False),
        sa.Column("recommendation_type", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("proposed_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("required_policy", sa.String(length=64), nullable=False),
        sa.Column("requires_user_approval", sa.Boolean(), nullable=False),
        sa.Column("shadow", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recommendation_id", name="uq_recommendations_id"),
    )
    op.create_index(
        "ix_recommendations_home_created",
        "recommendations",
        ["home_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_home_id"), "recommendations", ["home_id"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_recommendation_id"),
        "recommendations",
        ["recommendation_id"],
        unique=False,
    )
    op.create_table(
        "risk_cases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("home_id", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("room_id", sa.String(length=64), nullable=True),
        sa.Column("producer", sa.String(length=128), nullable=False),
        sa.Column("confirmed_by", sa.String(length=128), nullable=True),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('NORMAL','WATCH','PRE_ALERT','CONFIRMED',"
            "'ACTION_IN_PROGRESS','RECOVERY','CLOSED')",
            name="ck_risk_case_state",
        ),
        sa.CheckConstraint(
            "state NOT IN ('CONFIRMED','ACTION_IN_PROGRESS') OR confirmed_by IS NOT NULL",
            name="ck_risk_case_confirmed_by",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", name="uq_risk_cases_id"),
    )
    op.create_index(op.f("ix_risk_cases_case_id"), "risk_cases", ["case_id"], unique=False)
    op.create_index(op.f("ix_risk_cases_home_id"), "risk_cases", ["home_id"], unique=False)
    op.create_index("ix_risk_cases_home_state", "risk_cases", ["home_id", "state"], unique=False)
    op.create_table(
        "risk_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("origin", sa.String(length=32), nullable=False),
        sa.Column("capability", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=128), nullable=True),
        sa.Column("room_id", sa.String(length=64), nullable=True),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_risk_evidence_case_id"), "risk_evidence", ["case_id"], unique=False)
    op.create_table(
        "user_feedback",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("feedback_id", sa.Uuid(), nullable=False),
        sa.Column("home_id", sa.String(length=64), nullable=False),
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("action_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("modified_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('ACCEPT','REJECT','NOT_NOW','MODIFY','UNDO','NEVER_REPEAT')",
            name="ck_user_feedback_kind",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("feedback_id", name="uq_user_feedback_id"),
    )
    op.create_index(
        op.f("ix_user_feedback_feedback_id"), "user_feedback", ["feedback_id"], unique=False
    )
    op.create_index(op.f("ix_user_feedback_home_id"), "user_feedback", ["home_id"], unique=False)
    op.create_index(
        "ix_user_feedback_home_recorded", "user_feedback", ["home_id", "recorded_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_feedback_recommendation_id"),
        "user_feedback",
        ["recommendation_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Extend the append-only guarantee (Phase 2 created the function) to the
    # decision and action record. `syltra_forbid_mutation` already exists.
    append_only = (
        "policy_decisions",
        "action_requests",
        "action_attempts",
        "action_results",
        "user_feedback",
        "manual_overrides",
        "recommendations",
    )
    for table in append_only:
        op.execute(
            f"""
            CREATE TRIGGER {table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION syltra_forbid_mutation();
            """
        )

    # `risk_cases` and `contexts` are deliberately NOT append-only: a case
    # legitimately moves through its state machine, and a context is refreshed
    # as evidence changes. Their history lives in the event stream, and the
    # transitions themselves are recorded in `audit_events`, which is immutable.


def downgrade() -> None:
    for table in (
        "policy_decisions",
        "action_requests",
        "action_attempts",
        "action_results",
        "user_feedback",
        "manual_overrides",
        "recommendations",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table};")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_feedback_recommendation_id"), table_name="user_feedback")
    op.drop_index("ix_user_feedback_home_recorded", table_name="user_feedback")
    op.drop_index(op.f("ix_user_feedback_home_id"), table_name="user_feedback")
    op.drop_index(op.f("ix_user_feedback_feedback_id"), table_name="user_feedback")
    op.drop_table("user_feedback")
    op.drop_index(op.f("ix_risk_evidence_case_id"), table_name="risk_evidence")
    op.drop_table("risk_evidence")
    op.drop_index("ix_risk_cases_home_state", table_name="risk_cases")
    op.drop_index(op.f("ix_risk_cases_home_id"), table_name="risk_cases")
    op.drop_index(op.f("ix_risk_cases_case_id"), table_name="risk_cases")
    op.drop_table("risk_cases")
    op.drop_index(op.f("ix_recommendations_recommendation_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_home_id"), table_name="recommendations")
    op.drop_index("ix_recommendations_home_created", table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_policy_decisions_home_id"), table_name="policy_decisions")
    op.drop_index("ix_policy_decisions_home_evaluated", table_name="policy_decisions")
    op.drop_index(op.f("ix_policy_decisions_decision_id"), table_name="policy_decisions")
    op.drop_table("policy_decisions")
    op.drop_index(op.f("ix_manual_overrides_home_id"), table_name="manual_overrides")
    op.drop_index("ix_manual_overrides_home_at", table_name="manual_overrides")
    op.drop_table("manual_overrides")
    op.drop_index("ix_contexts_home_type", table_name="contexts")
    op.drop_index("ix_contexts_home_started", table_name="contexts")
    op.drop_index(op.f("ix_contexts_home_id"), table_name="contexts")
    op.drop_index(op.f("ix_contexts_context_id"), table_name="contexts")
    op.drop_table("contexts")
    op.drop_index(op.f("ix_context_evidence_context_id"), table_name="context_evidence")
    op.drop_table("context_evidence")
    op.drop_index(op.f("ix_action_results_home_id"), table_name="action_results")
    op.drop_index("ix_action_results_home_completed", table_name="action_results")
    op.drop_index(op.f("ix_action_results_action_id"), table_name="action_results")
    op.drop_table("action_results")
    op.drop_index(op.f("ix_action_requests_home_id"), table_name="action_requests")
    op.drop_index("ix_action_requests_home_created", table_name="action_requests")
    op.drop_index(op.f("ix_action_requests_decision_id"), table_name="action_requests")
    op.drop_index(op.f("ix_action_requests_action_id"), table_name="action_requests")
    op.drop_table("action_requests")
    op.drop_index(op.f("ix_action_attempts_action_id"), table_name="action_attempts")
    op.drop_table("action_attempts")
    # ### end Alembic commands ###
